spring:
  datasource:
    url: jdbc:mysql://${MYSQL_SERVER_SERVICE_SERVICE_HOST:http://localhost}:${MYSQL_SERVER_SERVICE_SERVICE_PORT:3306}/distribution_app?characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath:schema.sql
    data: classpath:data.sql
    initialization-mode: always
