spring:
  datasource:
    url: jdbc:mysql://localhost:3306/distribution_app?characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath:schema.sql
    data: classpath:data.sql