eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/, http://localhost:8082/eureka/

management:
  endpoint:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'